/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.auth.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param status 
 * @param message 
 * @param error 
 * @param `data` 
 */


data class ErrorResponse (

    @field:JsonProperty("status")
    val status: kotlin.Int? = null,

    @field:JsonProperty("message")
    val message: kotlin.String? = null,

    @field:JsonProperty("error")
    val error: kotlin.Any? = null,

    @field:JsonProperty("data")
    val `data`: kotlin.Any? = null

)

