/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.auth.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param tokenType Token type eg. \"Bearer\"
 * @param accessToken Access token, used to communicate with IOTConnect APIs
 * @param expiresIn Access token expiry duration in seconds, eg. 1000
 * @param refreshToken Refresh token, used to get new access token against current session without login request
 * @param status Status code of request, eg.200
 */


data class LoginResponse (

    /* Token type eg. \"Bearer\" */
    @field:JsonProperty("token_type")
    val tokenType: kotlin.String? = null,

    /* Access token, used to communicate with IOTConnect APIs */
    @field:JsonProperty("access_token")
    val accessToken: kotlin.String? = null,

    /* Access token expiry duration in seconds, eg. 1000 */
    @field:JsonProperty("expires_in")
    val expiresIn: kotlin.Long? = null,

    /* Refresh token, used to get new access token against current session without login request */
    @field:JsonProperty("refresh_token")
    val refreshToken: kotlin.String? = null,

    /* Status code of request, eg.200 */
    @field:JsonProperty("status")
    val status: Int = 0

)

