/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.auth.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param username Email id of company user, eg. demouser@gmail.com
 * @param password User's login password
 */

data class LoginRequest(

    /* Email id of company user, eg. demouser@gmail.com */
    @field:JsonProperty("username")
    val username: kotlin.String,

    /* User's login password */
    @field:JsonProperty("password")
    val password: kotlin.String,

)
