/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.auth.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param refreshtoken Refresh token
 */

data class RefreshTokenRequest(

    /* Refresh token */
    @field:JsonProperty("refreshtoken")
    val refreshtoken: kotlin.String,

)
