/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.user.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param guid 
 * @param title 
 * @param description 
 */


data class AnnouncementDetail (

    @field:JsonProperty("guid")
    val guid: kotlin.String? = null,

    @field:JsonProperty("Title")
    val title: kotlin.String? = null,

    @field:JsonProperty("Description")
    val description: kotlin.String? = null

)

