/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.user.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param authType * @param features */

data class AuthenticationFeatures(

    @field:JsonProperty("authType")
    val authType: kotlin.String? = null,

    @field:JsonProperty("features")
    val features: kotlin.Any? = null,

)
