/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.user.client.models

import com.thealvistar.iotconnect.user.client.models.UserInfo

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param name Entity Name
 * @param parentEntityGuid Parent Entity Guid
 * @param ownerUserGuid Entity owner user guid
 * @param isRemoveEntityOwner 
 * @param description Entity Description
 * @param childEntityLabel 
 * @param address Entity Address
 * @param address2 Entity Address 2
 * @param city City Name
 * @param stateGuid State Guid. You can fetch country wise state list from Master API
 * @param countryGuid Country Guid. You can fetch country list from Master API
 * @param zipCode Zip Code
 * @param timezoneGuid Timezone Guid. You can fetch timezone list from Master API
 * @param userInfo 
 * @param userInfoXml 
 */


data class EntityUpdateRequest (

    /* Entity Name */
    @field:JsonProperty("name")
    val name: kotlin.String,

    /* Parent Entity Guid */
    @field:JsonProperty("parentEntityGuid")
    val parentEntityGuid: kotlin.String,

    /* Entity owner user guid */
    @field:JsonProperty("ownerUserGuid")
    val ownerUserGuid: kotlin.String? = null,

    @field:JsonProperty("isRemoveEntityOwner")
    val isRemoveEntityOwner: kotlin.Boolean? = false,

    /* Entity Description */
    @field:JsonProperty("description")
    val description: kotlin.String? = null,

    @field:JsonProperty("childEntityLabel")
    val childEntityLabel: kotlin.String? = null,

    /* Entity Address */
    @field:JsonProperty("address")
    val address: kotlin.String? = null,

    /* Entity Address 2 */
    @field:JsonProperty("address2")
    val address2: kotlin.String? = null,

    /* City Name */
    @field:JsonProperty("city")
    val city: kotlin.String? = null,

    /* State Guid. You can fetch country wise state list from Master API */
    @field:JsonProperty("stateGuid")
    val stateGuid: kotlin.String? = null,

    /* Country Guid. You can fetch country list from Master API */
    @field:JsonProperty("countryGuid")
    val countryGuid: kotlin.String? = null,

    /* Zip Code */
    @field:JsonProperty("zipCode")
    val zipCode: kotlin.String? = null,

    /* Timezone Guid. You can fetch timezone list from Master API */
    @field:JsonProperty("timezoneGuid")
    val timezoneGuid: kotlin.String? = null,

    @field:JsonProperty("userInfo")
    val userInfo: UserInfo? = null,

    @field:JsonProperty("userInfoXml")
    val userInfoXml: kotlin.Any? = null

)

