/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.user.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param `data`
 * @param status
 * @param message
 * @param count
 */

data class EntityLookupResponse(

    @field:JsonProperty("data")
    val `data`: kotlin.collections.List<EntityLookup>? = null,

    @field:JsonProperty("status")
    val status: Int = 0,

    @field:JsonProperty("message")
    val message: kotlin.String? = null,

    @field:JsonProperty("count")
    val count: kotlin.Long? = null,

)
