/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.user.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param guid 
 * @param name 
 * @param parentEntityGuid 
 * @param description 
 * @param childEntityLabel 
 * @param companyGuid 
 * @param isDeleted 
 * @param createdDate 
 * @param createdBy 
 * @param updatedDate 
 * @param updatedBy 
 * @param address 
 * @param city 
 * @param stateGuid 
 * @param countryGuid 
 * @param timezoneGuid 
 * @param defaultuserGuid 
 * @param zipCode 
 * @param address2 
 * @param entityInfo 
 */


data class EntityDetail (

    @field:JsonProperty("guid")
    val guid: kotlin.String? = null,

    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    @field:JsonProperty("parentEntityGuid")
    val parentEntityGuid: kotlin.String? = null,

    @field:JsonProperty("description")
    val description: kotlin.String? = null,

    @field:JsonProperty("childEntityLabel")
    val childEntityLabel: kotlin.String? = null,

    @field:JsonProperty("companyGuid")
    val companyGuid: kotlin.String? = null,

    @field:JsonProperty("isDeleted")
    val isDeleted: kotlin.Boolean? = null,

    @field:JsonProperty("createdDate")
    val createdDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("createdBy")
    val createdBy: kotlin.String? = null,

    @field:JsonProperty("updatedDate")
    val updatedDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("updatedBy")
    val updatedBy: kotlin.String? = null,

    @field:JsonProperty("address")
    val address: kotlin.String? = null,

    @field:JsonProperty("city")
    val city: kotlin.String? = null,

    @field:JsonProperty("stateGuid")
    val stateGuid: kotlin.String? = null,

    @field:JsonProperty("countryGuid")
    val countryGuid: kotlin.String? = null,

    @field:JsonProperty("timezoneGuid")
    val timezoneGuid: kotlin.String? = null,

    @field:JsonProperty("defaultuserGuid")
    val defaultuserGuid: kotlin.String? = null,

    @field:JsonProperty("zipCode")
    val zipCode: kotlin.String? = null,

    @field:JsonProperty("address2")
    val address2: kotlin.String? = null,

    @field:JsonProperty("entityInfo")
    val entityInfo: kotlin.Any? = null

)

