/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.user.client.models

import com.thealvistar.iotconnect.user.client.models.PropertyValue

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param properties Custom Properties
 * @param xmlProperties 
 */


data class EntityPropertiesUpdateRequest (

    /* Custom Properties */
    @field:JsonProperty("properties")
    val properties: kotlin.collections.List<PropertyValue>? = null,

    @field:JsonProperty("xmlProperties")
    val xmlProperties: kotlin.Any? = null

)

