/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.user.client.models

import com.thealvistar.iotconnect.user.client.models.UserUploadData

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param user 
 */


data class Error (

    @field:JsonProperty("user")
    val user: UserUploadData? = null

)

