/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.user.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param timeZoneGuid Timezone Guid. You can fetch timezone list from Master API.
 * @param emailNotification true or false. To turn on/off email notifications.
 * @param smsNotification true or false. To turn on/off sms notifications.
 * @param pushNotification true or false. To turn on/off push notifications.
 * @param pageSize Your preference for number of records in one page. eg: 25
 * @param languageGuid Language Guid.You can fetch language list from Master API.
 * @param emailNotifyOn Email notification preference. 0: to receive emails on primary email id, 1: to receive emails on alternate email id.
 * @param alternateEmailID To receive email notifications on secondary email address. if <i>emailNotifyOn</i> is 1.
 * @param platformEmails Your preference for PlatformEmails.Store BIT wise sum or the value of email types
 * @param oldView true or false. To switch from old and new UI view.
 */


data class PreferenceUpdateRequest (

    /* Timezone Guid. You can fetch timezone list from Master API. */
    @field:JsonProperty("timeZoneGuid")
    val timeZoneGuid: kotlin.String,

    /* true or false. To turn on/off email notifications. */
    @field:JsonProperty("emailNotification")
    val emailNotification: kotlin.Boolean,

    /* true or false. To turn on/off sms notifications. */
    @field:JsonProperty("smsNotification")
    val smsNotification: kotlin.Boolean,

    /* true or false. To turn on/off push notifications. */
    @field:JsonProperty("pushNotification")
    val pushNotification: kotlin.Boolean,

    /* Your preference for number of records in one page. eg: 25 */
    @field:JsonProperty("pageSize")
    val pageSize: kotlin.Int,

    /* Language Guid.You can fetch language list from Master API. */
    @field:JsonProperty("languageGuid")
    val languageGuid: kotlin.String,

    /* Email notification preference. 0: to receive emails on primary email id, 1: to receive emails on alternate email id. */
    @field:JsonProperty("emailNotifyOn")
    val emailNotifyOn: kotlin.Int? = null,

    /* To receive email notifications on secondary email address. if <i>emailNotifyOn</i> is 1. */
    @field:JsonProperty("alternateEmailID")
    val alternateEmailID: kotlin.String? = null,

    /* Your preference for PlatformEmails.Store BIT wise sum or the value of email types */
    @field:JsonProperty("platformEmails")
    val platformEmails: kotlin.Int? = null,

    /* true or false. To switch from old and new UI view. */
    @field:JsonProperty("oldView")
    val oldView: kotlin.Boolean? = null

)

