/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.user.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param email User's Login email Id. eg: abc@gmail.com
 * @param invitationguid Invitation Guid
 * @param newpassword New login password
 */


data class ResetPasswordRequest (

    /* User's Login email Id. eg: abc@gmail.com */
    @field:JsonProperty("email")
    val email: kotlin.String,

    /* Invitation Guid */
    @field:JsonProperty("invitationguid")
    val invitationguid: kotlin.String,

    /* New login password */
    @field:JsonProperty("newpassword")
    val newpassword: kotlin.String

)

