/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.user.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param guid * @param timeZoneGuid * @param emailNotification * @param emailNotifyOn * @param alternateEmailID * @param smsNotification * @param pushNotification * @param pageSize * @param platformEmails * @param oldView * @param languageGuid */

data class UserPreferenceList(

    @field:JsonProperty("guid")
    val guid: kotlin.String? = null,

    @field:JsonProperty("timeZoneGuid")
    val timeZoneGuid: kotlin.String? = null,

    @field:JsonProperty("emailNotification")
    val emailNotification: kotlin.Boolean? = null,

    @field:JsonProperty("emailNotifyOn")
    val emailNotifyOn: kotlin.Int? = null,

    @field:JsonProperty("alternateEmailID")
    val alternateEmailID: kotlin.String? = null,

    @field:JsonProperty("smsNotification")
    val smsNotification: kotlin.Boolean? = null,

    @field:JsonProperty("pushNotification")
    val pushNotification: kotlin.Boolean? = null,

    @field:JsonProperty("pageSize")
    val pageSize: kotlin.Int? = null,

    @field:JsonProperty("platformEmails")
    val platformEmails: kotlin.Int? = null,

    @field:JsonProperty("oldView")
    val oldView: kotlin.Boolean? = null,

    @field:JsonProperty("languageGuid")
    val languageGuid: kotlin.String? = null,

)
