/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.user.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param userGuid 
 * @param preferenceAction 
 * @param userPreferenceGuid 
 * @param emailNotification 
 * @param smsNotification 
 * @param alternateEmailID 
 * @param pushNotification 
 * @param pageSize 
 */


data class UserPreferenceUpdate (

    @field:JsonProperty("userGuid")
    val userGuid: kotlin.String? = null,

    @field:JsonProperty("preferenceAction")
    val preferenceAction: kotlin.String? = null,

    @field:JsonProperty("userPreferenceGuid")
    val userPreferenceGuid: kotlin.String? = null,

    @field:JsonProperty("emailNotification")
    val emailNotification: kotlin.Boolean? = null,

    @field:JsonProperty("smsNotification")
    val smsNotification: kotlin.Boolean? = null,

    @field:JsonProperty("alternateEmailID")
    val alternateEmailID: kotlin.String? = null,

    @field:JsonProperty("pushNotification")
    val pushNotification: kotlin.Boolean? = null,

    @field:JsonProperty("pageSize")
    val pageSize: kotlin.Int? = null

)

