/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.user.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param guid
 * @param userId
 * @param companyGuid
 * @param firstName
 * @param lastName
 * @param name
 * @param contactNo
 * @param timezoneGuid
 * @param imageName
 * @param isActive
 * @param isVerified
 * @param isLocked
 * @param userInfo
 * @param roleGuid
 * @param roleName
 * @param createdBy
 * @param updatedBy
 * @param createdDate
 * @param updatedDate
 * @param entityGuid
 * @param entityName
 * @param imageUrl
 * @param invitationguid
 */

data class UserGetList(

    @field:JsonProperty("guid")
    val guid: kotlin.String? = null,

    @field:JsonProperty("userId")
    val userId: kotlin.String? = null,

    @field:JsonProperty("companyGuid")
    val companyGuid: kotlin.String? = null,

    @field:JsonProperty("firstName")
    val firstName: kotlin.String? = null,

    @field:JsonProperty("lastName")
    val lastName: kotlin.String? = null,

    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    @field:JsonProperty("contactNo")
    val contactNo: kotlin.String? = null,

    @field:JsonProperty("timezoneGuid")
    val timezoneGuid: kotlin.String? = null,

    @field:JsonProperty("imageName")
    val imageName: kotlin.String? = null,

    @field:JsonProperty("isActive")
    val isActive: kotlin.Boolean? = null,

    @field:JsonProperty("isVerified")
    val isVerified: kotlin.Boolean? = null,

    @field:JsonProperty("isLocked")
    val isLocked: kotlin.Boolean? = null,

    @field:JsonProperty("userInfo")
    val userInfo: kotlin.collections.List<kotlin.Any>? = null,

    @field:JsonProperty("roleGuid")
    val roleGuid: kotlin.String? = null,

    @field:JsonProperty("roleName")
    val roleName: kotlin.String? = null,

    @field:JsonProperty("createdBy")
    val createdBy: kotlin.String? = null,

    @field:JsonProperty("updatedBy")
    val updatedBy: kotlin.String? = null,

    @field:JsonProperty("createdDate")
    val createdDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("updatedDate")
    val updatedDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("entityGuid")
    val entityGuid: kotlin.String? = null,

    @field:JsonProperty("entityName")
    val entityName: kotlin.String? = null,

    @field:JsonProperty("imageUrl")
    val imageUrl: kotlin.String? = null,

    @field:JsonProperty("invitationguid")
    val invitationguid: kotlin.String? = null,

)
