/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.user.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param roleUserGuid * @param isActive * @param userId * @param roleGuid * @param isUpdateRole * @param entityGuid */

data class UserUpdateByID(

    @field:JsonProperty("roleUserGuid ")
    val roleUserGuid: kotlin.String? = null,

    @field:JsonProperty("isActive")
    val isActive: kotlin.Boolean? = null,

    @field:JsonProperty("userId")
    val userId: kotlin.String? = null,

    @field:JsonProperty("roleGuid ")
    val roleGuid: kotlin.String? = null,

    @field:JsonProperty("isUpdateRole")
    val isUpdateRole: kotlin.Boolean? = null,

    @field:JsonProperty("entityGuid ")
    val entityGuid: kotlin.String? = null,

)
