/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.user.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param guid 
 * @param name 
 * @param options 
 * @param fieldType 
 * @param `value` 
 */


data class UserinfoValues (

    @field:JsonProperty("guid")
    val guid: kotlin.String? = null,

    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    @field:JsonProperty("options")
    val options: kotlin.String? = null,

    @field:JsonProperty("fieldType")
    val fieldType: kotlin.String? = null,

    @field:JsonProperty("value")
    val `value`: kotlin.String? = null

)

