/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.user.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param firstName User's first name
 * @param lastName User's last name
 * @param timezoneGuid Timezone Guid. You can fetch timezone list from Master API
 * @param roleGuid Role Guid
 * @param entityGuid Entity Guid
 * @param properties Custom properties allows you to add additional information about user. You can add multiple custom properties.
 * @param xmlProperties * @param contactNo User's contact no. eg: 91-1234567890
 */

data class UserUpdateRequest(

    /* User's first name */
    @field:JsonProperty("firstName")
    val firstName: kotlin.String,

    /* User's last name */
    @field:JsonProperty("lastName")
    val lastName: kotlin.String,

    /* Timezone Guid. You can fetch timezone list from Master API */
    @field:JsonProperty("timezoneGuid")
    val timezoneGuid: kotlin.String,

    /* Role Guid */
    @field:JsonProperty("roleGuid")
    val roleGuid: kotlin.String,

    /* Entity Guid */
    @field:JsonProperty("entityGuid")
    val entityGuid: kotlin.String,

    /* Custom properties allows you to add additional information about user. You can add multiple custom properties. */
    @field:JsonProperty("properties")
    val properties: kotlin.collections.List<PropertyValue>? = null,

    @field:JsonProperty("xmlProperties")
    val xmlProperties: kotlin.Any? = null,

    /* User's contact no. eg: 91-1234567890 */
    @field:JsonProperty("contactNo")
    val contactNo: kotlin.String? = null,

)
