/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param groupId 
 * @param groupType 
 * @param tags 
 * @param createdDateTime 
 */


data class ADUGroupCreate (

    @field:JsonProperty("groupId")
    val groupId: kotlin.String? = null,

    @field:JsonProperty("groupType")
    val groupType: ADUGroupCreate.GroupType? = null,

    @field:JsonProperty("tags")
    val tags: kotlin.collections.List<kotlin.String>? = null,

    @field:JsonProperty("createdDateTime")
    val createdDateTime: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: _0,_1,_2
     */
    enum class GroupType(val value: kotlin.Int) {
        @JsonProperty(value = "0") _0(0),
        @JsonProperty(value = "1") _1(1),
        @JsonProperty(value = "2") _2(2);
    }
}

