/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param sequence Attribute's new sequence number
 * @param deviceTemplateGuid Associated device template guid.
 */


data class AttributeUpdateSequenceRequest (

    /* Attribute's new sequence number */
    @field:JsonProperty("sequence")
    val sequence: kotlin.Int,

    /* Associated device template guid. */
    @field:JsonProperty("deviceTemplateGuid")
    val deviceTemplateGuid: kotlin.String

)

