/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param localName Child attribute's name.   It should be alphanumeric and allows two consecutive '_' and must start with the alphabet.   Eg. Temperature, Humadity, oxygenIn1, Temperature_In, Temperature__Out, Oxygen_In__1  etc.
 * @param dataTypeGuid Child attribute's datatype guid, Object datatype is not allowed for child attributes.
 * @param description Child attribute's description
 * @param dataValidation Child attribute's data validation.   Type validation values and/or validation ranges separated by commas.<div> For example: </div><div>  1, 2, 10 to 20 </div> -10 to -5, -15 <div> Red, Green, Blue</div>
 * @param sequence Child attribute's sequence
 * @param unit Child attribute's unit
 * @param startIndex Start index is required if the associated device template has enabled low bandwidth support.
 * @param numChar Range is required if the associated device template has enabled low bandwidth support.
 * @param attributeColor Color Code of attribute.
 */

data class AttributeBaseObject(

    /* Child attribute's name.   It should be alphanumeric and allows two consecutive '_' and must start with the alphabet.   Eg. Temperature, Humadity, oxygenIn1, Temperature_In, Temperature__Out, Oxygen_In__1  etc. */
    @field:JsonProperty("localName")
    val localName: kotlin.String,

    /* Child attribute's datatype guid, Object datatype is not allowed for child attributes. */
    @field:JsonProperty("dataTypeGuid")
    val dataTypeGuid: kotlin.String,

    /* Child attribute's description */
    @field:JsonProperty("description")
    val description: kotlin.String? = null,

    /* Child attribute's data validation.   Type validation values and/or validation ranges separated by commas.<div> For example: </div><div>  1, 2, 10 to 20 </div> -10 to -5, -15 <div> Red, Green, Blue</div> */
    @field:JsonProperty("dataValidation")
    val dataValidation: kotlin.String? = null,

    /* Child attribute's sequence */
    @field:JsonProperty("sequence")
    val sequence: kotlin.Int? = null,

    /* Child attribute's unit */
    @field:JsonProperty("unit")
    val unit: kotlin.String? = null,

    /* Start index is required if the associated device template has enabled low bandwidth support. */
    @field:JsonProperty("startIndex")
    val startIndex: kotlin.Int? = null,

    /* Range is required if the associated device template has enabled low bandwidth support. */
    @field:JsonProperty("numChar")
    val numChar: kotlin.Int? = null,

    /* Color Code of attribute. */
    @field:JsonProperty("attributeColor")
    val attributeColor: kotlin.String? = null,

)
