/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param guid 
 * @param uniqueId 
 * @param displayName 
 * @param tag 
 * @param isConnected 
 * @param lastactivityDate 
 * @param isActive 
 * @param firmwareupgradeGuid 
 * @param deviceTemplateGuid 
 * @param deviceTemplateName 
 * @param reportingTo 
 * @param entityName 
 * @param isAcquired 
 * @param lastCommunication 
 */


data class ChildDeviceList (

    @field:JsonProperty("guid")
    val guid: kotlin.String? = null,

    @field:JsonProperty("uniqueId")
    val uniqueId: kotlin.String? = null,

    @field:JsonProperty("displayName")
    val displayName: kotlin.String? = null,

    @field:JsonProperty("tag")
    val tag: kotlin.String? = null,

    @field:JsonProperty("isConnected")
    val isConnected: kotlin.Boolean? = null,

    @field:JsonProperty("lastactivityDate")
    val lastactivityDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("isActive")
    val isActive: kotlin.Boolean? = null,

    @field:JsonProperty("firmwareupgradeGuid")
    val firmwareupgradeGuid: kotlin.String? = null,

    @field:JsonProperty("deviceTemplateGuid")
    val deviceTemplateGuid: kotlin.String? = null,

    @field:JsonProperty("deviceTemplateName")
    val deviceTemplateName: kotlin.String? = null,

    @field:JsonProperty("reportingTo")
    val reportingTo: kotlin.String? = null,

    @field:JsonProperty("entityName")
    val entityName: kotlin.String? = null,

    @field:JsonProperty("isAcquired")
    val isAcquired: kotlin.Boolean? = null,

    @field:JsonProperty("lastCommunication")
    val lastCommunication: java.time.OffsetDateTime? = null

)

