/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param ackId Command History Guid
 * @param status New Status Code. 0: In Queue, 1: In Transit, 2: Failed, 3: Executed
 * @param statusText Status Text
 */


data class CommandHistoryUpdateRequest (

    /* Command History Guid */
    @field:JsonProperty("ackId")
    val ackId: java.util.UUID,

    /* New Status Code. 0: In Queue, 1: In Transit, 2: Failed, 3: Executed */
    @field:JsonProperty("status")
    val status: kotlin.Int,

    /* Status Text */
    @field:JsonProperty("statusText")
    val statusText: kotlin.String? = null

)

