/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param isActive Scheduled Command Active Status : true/false
 */

data class CommandScheduleUpdateStatusRequest(

    /* Scheduled Command Active Status : true/false */
    @field:JsonProperty("isActive")
    val isActive: kotlin.Boolean,

)
