/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models

import com.thealvistar.iotconnect.device.client.models.BatchCommandDevice

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param guid 
 * @param name 
 * @param command 
 * @param createdDate 
 * @param updatedDate 
 * @param requiredParam 
 * @param requiredAck 
 * @param isOTACommand 
 * @param tag 
 * @param isTemplateCommandUsed 
 * @param devices 
 */


data class CommandList (

    @field:JsonProperty("guid")
    val guid: kotlin.String? = null,

    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    @field:JsonProperty("command")
    val command: kotlin.String? = null,

    @field:JsonProperty("createdDate")
    val createdDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("updatedDate")
    val updatedDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("requiredParam")
    val requiredParam: kotlin.Boolean? = null,

    @field:JsonProperty("requiredAck")
    val requiredAck: kotlin.Boolean? = null,

    @field:JsonProperty("isOTACommand")
    val isOTACommand: kotlin.Boolean? = null,

    @field:JsonProperty("tag")
    val tag: kotlin.String? = null,

    @field:JsonProperty("isTemplateCommandUsed")
    val isTemplateCommandUsed: kotlin.Boolean? = null,

    @field:JsonProperty("devices")
    val devices: kotlin.collections.List<BatchCommandDevice>? = null

)

