/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param startDate Start date format should be YYYY-MM-DD
 * @param exportType Export Type : 1 for Template, 2 for Entity and 3 for Device
 * @param guids Guid list for selected export type. For example, if exportType is template then send template guid list.
 * @param endDate */

data class CosmosExportHistoryRequest(

    /* Start date format should be YYYY-MM-DD */
    @field:JsonProperty("startDate")
    val startDate: kotlin.String,

    /* Export Type : 1 for Template, 2 for Entity and 3 for Device */
    @field:JsonProperty("exportType")
    val exportType: CosmosExportHistoryRequest.ExportType,

    /* Guid list for selected export type. For example, if exportType is template then send template guid list. */
    @field:JsonProperty("guids")
    val guids: kotlin.collections.List<kotlin.String>,

    @field:JsonProperty("endDate")
    val endDate: kotlin.String? = null,

) {

    /**
     * Export Type : 1 for Template, 2 for Entity and 3 for Device
     *
     * Values: _1,_2,_3
     */
    enum class ExportType(val value: kotlin.Int) {
        @JsonProperty(value = "1")
        _1(1),

        @JsonProperty(value = "2")
        _2(2),

        @JsonProperty(value = "3")
        _3(3),
    }
}
