/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param guid 
 * @param companyGuid 
 * @param exportType 
 * @param startDate 
 * @param endDate 
 * @param ruUsed 
 * @param charges 
 * @param status 
 * @param userId 
 * @param createdDate 
 * @param requestData 
 */


data class CosmosExportHistoryList (

    @field:JsonProperty("guid")
    val guid: kotlin.String? = null,

    @field:JsonProperty("companyGuid")
    val companyGuid: kotlin.String? = null,

    @field:JsonProperty("exportType")
    val exportType: kotlin.String? = null,

    @field:JsonProperty("startDate")
    val startDate: kotlin.String? = null,

    @field:JsonProperty("endDate")
    val endDate: kotlin.String? = null,

    @field:JsonProperty("ruUsed")
    val ruUsed: kotlin.Int? = null,

    @field:JsonProperty("charges")
    val charges: kotlin.Double? = null,

    @field:JsonProperty("status")
    val status: kotlin.String? = null,

    @field:JsonProperty("userId")
    val userId: kotlin.String? = null,

    @field:JsonProperty("createdDate")
    val createdDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("requestData")
    val requestData: kotlin.String? = null

)

