/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param updateInfo * @param aduGroup * @param deploymentTime */

data class DeploymentCreateRequest(

    @field:JsonProperty("updateInfo")
    val updateInfo: DeviceUpdate? = null,

    @field:JsonProperty("adu-group")
    val aduGroup: kotlin.String? = null,

    @field:JsonProperty("deploymentTime")
    val deploymentTime: java.time.OffsetDateTime? = null,

)
