/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param deploymentId * @param deploymentType * @param deviceGroupType * @param startDateTime * @param isCompleted */

data class DeploymentList(

    @field:JsonProperty("deploymentId")
    val deploymentId: kotlin.String? = null,

    @field:JsonProperty("deploymentType")
    val deploymentType: kotlin.String? = null,

    @field:JsonProperty("deviceGroupType")
    val deviceGroupType: kotlin.String? = null,

    @field:JsonProperty("startDateTime")
    val startDateTime: java.time.OffsetDateTime? = null,

    @field:JsonProperty("isCompleted")
    val isCompleted: kotlin.Boolean? = null,

)
