/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param userId 
 * @param userGuid 
 * @param errorLog 
 */


data class DeviceGrantEmailsUpdate (

    @field:JsonProperty("userId")
    val userId: kotlin.String? = null,

    @field:JsonProperty("userGuid")
    val userGuid: kotlin.String? = null,

    @field:JsonProperty("errorLog")
    val errorLog: kotlin.String? = null

)

