/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param isActive Device Active Status, 'true' for making device active and 'false' for making device inactive
 */

data class DeviceUpdateStatusRequest(

    /* Device Active Status, 'true' for making device active and 'false' for making device inactive */
    @field:JsonProperty("isActive")
    val isActive: kotlin.Boolean,

)
