/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param uniqueId * @param fromDate * @param toDate * @param continuationToken * @param pageNumber * @param pageSize * @param searchText * @param sortBy */

data class DeviceDiagnosticsV2Request(

    @field:JsonProperty("uniqueId")
    val uniqueId: kotlin.String? = null,

    @field:JsonProperty("fromDate")
    val fromDate: kotlin.String? = null,

    @field:JsonProperty("toDate")
    val toDate: kotlin.String? = null,

    @field:JsonProperty("continuationToken")
    val continuationToken: kotlin.String? = null,

    @field:JsonProperty("pageNumber")
    val pageNumber: kotlin.Int? = null,

    @field:JsonProperty("pageSize")
    val pageSize: kotlin.Int? = null,

    @field:JsonProperty("searchText")
    val searchText: kotlin.String? = null,

    @field:JsonProperty("sortBy")
    val sortBy: kotlin.String? = null,

)
