/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param tag 
 * @param uniqueIds 
 */


data class DeviceBulkTagAssignRequest (

    @field:JsonProperty("tag")
    val tag: kotlin.String? = null,

    @field:JsonProperty("uniqueIds")
    val uniqueIds: kotlin.collections.List<kotlin.String>? = null

)

