/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param toDate To date time for archive data which are older then this date time   Date format should be YYYY-MM-DD
 * @param supportTicketNumber Support ticket number for archive device data
 */


data class DeviceDataArchiveRequest (

    /* To date time for archive data which are older then this date time   Date format should be YYYY-MM-DD */
    @field:JsonProperty("toDate")
    val toDate: kotlin.String,

    /* Support ticket number for archive device data */
    @field:JsonProperty("supportTicketNumber")
    val supportTicketNumber: kotlin.String? = null

)

