/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param localName The twin property name of device.
 * @param desiredValue The twin property value of device. twin property value should be valid as per device template setting datatype.
 * @param templateSettingGuid Template Setting Guid
 */


data class DeviceTwinRequest (

    /* The twin property name of device. */
    @field:JsonProperty("localName")
    val localName: kotlin.String,

    /* The twin property value of device. twin property value should be valid as per device template setting datatype. */
    @field:JsonProperty("desiredValue")
    val desiredValue: kotlin.String,

    /* Template Setting Guid */
    @field:JsonProperty("templateSettingGuid")
    val templateSettingGuid: kotlin.String

)

