/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models

import com.thealvistar.iotconnect.device.client.models.PropertyValue

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param properties 
 * @param xmlProperties 
 */


data class DevicePropertyUpdateRequest (

    @field:JsonProperty("properties")
    val properties: kotlin.collections.List<PropertyValue>,

    @field:JsonProperty("xmlProperties")
    val xmlProperties: kotlin.Any? = null

)

