/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param templateDirectMethodGuid Template Direct Method Guid
 * @param methodName MethodName
 * @param responseTimeoutInSeconds Response timeout seconds
 * @param payload Direct method payload
 */

data class DeviceDirectMethodRequest(

    /* Template Direct Method Guid */
    @field:JsonProperty("templateDirectMethodGuid")
    val templateDirectMethodGuid: java.util.UUID,

    /* MethodName */
    @field:JsonProperty("methodName")
    val methodName: kotlin.String,

    /* Response timeout seconds */
    @field:JsonProperty("responseTimeoutInSeconds")
    val responseTimeoutInSeconds: kotlin.Int,

    /* Direct method payload */
    @field:JsonProperty("payload")
    val payload: kotlin.Any,

)
