/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models

import com.thealvistar.iotconnect.device.client.models.PropertyValue

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param uniqueId The uniqueId of device.  <b>Notes:</b> Device uniqueId length is conditional based on device template auth type and device type   1. Self or CA signed parent device uniqueId length should be less than or equal to 31 characters.   2. Self or CA signed child device uniqueId length should be less than or equal to 31 characters.   3. For TPM or key, all device uniqueId length should be less than or equal to 128 characters.
 * @param deviceTemplateGuid The deviceTemplateGuid of device.
 * @param displayName The display name of device.
 * @param entityGuid The entityGuid of device.
 * @param firmwareUpgradeGuid The firmwareUpgradeGuid of device.
 * @param tag The tag of the device which must be exists in device template. This field is required if the request for child device create and gateway support enabled in device template.
 * @param parentDeviceGuid The gateway device guid. This field is required if the request for child device create and gateway support enabled in device template.
 * @param primaryThumbprint The primaryThumbprint of self signed device. This field is required if device template authentication type is self signed certificate.
 * @param secondaryThumbprint The secondaryThumbprint of self signed device.
 * @param endorsementKey The endorsementKey of TPM device. This field is required if device template authentication type is TPM.
 * @param properties The custom properties of device.
 * @param xmlProperties 
 * @param deviceCertificateGuid The certificateGuid of devicetemplate.
 * @param deviceCertificate Byte array of device certificate file(Only .pfx file allowed).
 * @param deviceCertificatePassword Password of device certificate
 * @param primaryKey The primaryKey of symmetric key device. This field is required if device template authentication type is symmetric key.
 * @param secondaryKey The secondaryKey of symmetric key device. This field is required if device template authentication type is symmetric key.
 * @param certificateText 
 * @param note The note of the device.
 */


data class DeviceCreateRequest (

    /* The uniqueId of device.  <b>Notes:</b> Device uniqueId length is conditional based on device template auth type and device type   1. Self or CA signed parent device uniqueId length should be less than or equal to 31 characters.   2. Self or CA signed child device uniqueId length should be less than or equal to 31 characters.   3. For TPM or key, all device uniqueId length should be less than or equal to 128 characters. */
    @field:JsonProperty("uniqueId")
    val uniqueId: kotlin.String,

    /* The deviceTemplateGuid of device. */
    @field:JsonProperty("deviceTemplateGuid")
    val deviceTemplateGuid: kotlin.String,

    /* The display name of device. */
    @field:JsonProperty("displayName")
    val displayName: kotlin.String,

    /* The entityGuid of device. */
    @field:JsonProperty("entityGuid")
    val entityGuid: kotlin.String,

    /* The firmwareUpgradeGuid of device. */
    @field:JsonProperty("firmwareUpgradeGuid")
    val firmwareUpgradeGuid: kotlin.String? = null,

    /* The tag of the device which must be exists in device template. This field is required if the request for child device create and gateway support enabled in device template. */
    @field:JsonProperty("tag")
    val tag: kotlin.String? = null,

    /* The gateway device guid. This field is required if the request for child device create and gateway support enabled in device template. */
    @field:JsonProperty("parentDeviceGuid")
    val parentDeviceGuid: kotlin.String? = null,

    /* The primaryThumbprint of self signed device. This field is required if device template authentication type is self signed certificate. */
    @field:JsonProperty("primaryThumbprint")
    val primaryThumbprint: kotlin.String? = null,

    /* The secondaryThumbprint of self signed device. */
    @field:JsonProperty("secondaryThumbprint")
    val secondaryThumbprint: kotlin.String? = null,

    /* The endorsementKey of TPM device. This field is required if device template authentication type is TPM. */
    @field:JsonProperty("endorsementKey")
    val endorsementKey: kotlin.String? = null,

    /* The custom properties of device. */
    @field:JsonProperty("properties")
    val properties: kotlin.collections.List<PropertyValue>? = null,

    @field:JsonProperty("xmlProperties")
    val xmlProperties: kotlin.Any? = null,

    /* The certificateGuid of devicetemplate. */
    @field:JsonProperty("deviceCertificateGuid")
    val deviceCertificateGuid: kotlin.String? = null,

    /* Byte array of device certificate file(Only .pfx file allowed). */
    @field:JsonProperty("deviceCertificate")
    val deviceCertificate: kotlin.ByteArray? = null,

    /* Password of device certificate */
    @field:JsonProperty("deviceCertificatePassword")
    val deviceCertificatePassword: kotlin.String? = null,

    /* The primaryKey of symmetric key device. This field is required if device template authentication type is symmetric key. */
    @field:JsonProperty("primaryKey")
    val primaryKey: kotlin.String? = null,

    /* The secondaryKey of symmetric key device. This field is required if device template authentication type is symmetric key. */
    @field:JsonProperty("secondaryKey")
    val secondaryKey: kotlin.String? = null,

    @field:JsonProperty("certificateText")
    val certificateText: kotlin.String? = null,

    /* The note of the device. */
    @field:JsonProperty("note")
    val note: kotlin.String? = null

)

