/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param deviceguid The device guid of device, Duplicate device guid not allowed.
 */

data class DeviceGuids(

    /* The device guid of device, Duplicate device guid not allowed. */
    @field:JsonProperty("deviceguid")
    val deviceguid: kotlin.String,

)
