/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param uniqueId * @param authType * @param maskedIpAddress * @param statusCode * @param time * @param operationName * @param category * @param level * @param resultDescription * @param location * @param partitionKey * @param rowKey * @param timestamp * @param eTag * @param properties */

data class DeviceDiagnostics(

    @field:JsonProperty("uniqueId")
    val uniqueId: kotlin.String? = null,

    @field:JsonProperty("authType")
    val authType: kotlin.String? = null,

    @field:JsonProperty("maskedIpAddress")
    val maskedIpAddress: kotlin.String? = null,

    @field:JsonProperty("statusCode")
    val statusCode: kotlin.String? = null,

    @field:JsonProperty("time")
    val time: java.time.OffsetDateTime? = null,

    @field:JsonProperty("operationName")
    val operationName: kotlin.String? = null,

    @field:JsonProperty("category")
    val category: kotlin.String? = null,

    @field:JsonProperty("level")
    val level: kotlin.String? = null,

    @field:JsonProperty("resultDescription")
    val resultDescription: kotlin.String? = null,

    @field:JsonProperty("location")
    val location: kotlin.String? = null,

    @field:JsonProperty("partitionKey")
    val partitionKey: kotlin.String? = null,

    @field:JsonProperty("rowKey")
    val rowKey: kotlin.String? = null,

    @field:JsonProperty("timestamp")
    val timestamp: java.time.OffsetDateTime? = null,

    @field:JsonProperty("eTag")
    val eTag: kotlin.String? = null,

    @field:JsonProperty("properties")
    val properties: kotlin.String? = null,

)
