/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param guid 
 * @param companyGuid 
 * @param templateSettingGuid 
 * @param deviceGuid 
 * @param createdDate 
 * @param sdkDate 
 * @param gatewayDate 
 * @param deviceDate 
 * @param desiredValue 
 * @param reportedValue 
 * @param desiredUpdatedDate 
 * @param reportedUpdatedDate 
 * @param desiredVersion 
 * @param name 
 * @param localName 
 * @param dataTypeName 
 * @param cpId 
 * @param uniqueId 
 * @param daTypeGuid 
 * @param isFault 
 * @param entityGuid 
 * @param isReadOnly 
 */


data class DeviceTwinList (

    @field:JsonProperty("guid")
    val guid: kotlin.String? = null,

    @field:JsonProperty("companyGuid")
    val companyGuid: kotlin.String? = null,

    @field:JsonProperty("templateSettingGuid")
    val templateSettingGuid: kotlin.String? = null,

    @field:JsonProperty("deviceGuid")
    val deviceGuid: kotlin.String? = null,

    @field:JsonProperty("createdDate")
    val createdDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("sdkDate")
    val sdkDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("gatewayDate")
    val gatewayDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("deviceDate")
    val deviceDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("desiredValue")
    val desiredValue: kotlin.String? = null,

    @field:JsonProperty("reportedValue")
    val reportedValue: kotlin.String? = null,

    @field:JsonProperty("desiredUpdatedDate")
    val desiredUpdatedDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("reportedUpdatedDate")
    val reportedUpdatedDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("desiredVersion")
    val desiredVersion: kotlin.String? = null,

    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    @field:JsonProperty("localName")
    val localName: kotlin.String? = null,

    @field:JsonProperty("dataTypeName")
    val dataTypeName: kotlin.String? = null,

    @field:JsonProperty("cpId")
    val cpId: kotlin.String? = null,

    @field:JsonProperty("uniqueId")
    val uniqueId: kotlin.String? = null,

    @field:JsonProperty("daTypeGuid")
    val daTypeGuid: kotlin.String? = null,

    @field:JsonProperty("isFault")
    val isFault: kotlin.Boolean? = null,

    @field:JsonProperty("entityGuid")
    val entityGuid: java.util.UUID? = null,

    @field:JsonProperty("isReadOnly")
    val isReadOnly: kotlin.Boolean? = null

)

