/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models

import com.thealvistar.iotconnect.device.client.models.DeviceProperty
import com.thealvistar.iotconnect.device.client.models.OutputparamListResponse

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param guid 
 * @param uniqueId 
 * @param displayName 
 * @param isConnected 
 * @param lastactivityDate 
 * @param isActive 
 * @param firmwareupgradeGuid 
 * @param deviceTemplateGuid 
 * @param authType 
 * @param authenticationType 
 * @param messageVersion 
 * @param isSolutionTemplate 
 * @param solutionName 
 * @param deviceInfo 
 * @param deviceTemplateName 
 * @param reportingTo 
 * @param entityName 
 * @param isAcquired 
 * @param childDeviceCount 
 * @param isType2Support 
 * @param isAllottedDevice 
 * @param allottedDevicePermission 
 * @param count 
 * @param isSharedDevice 
 * @param properties 
 * @param deviceStatus 
 * @param recentAttrValue 
 * @param isDpsDevice 
 * @param lastConnection 
 * @param lastCommunication 
 * @param solutionGuid 
 * @param groupName 
 * @param productName 
 * @param parentCompanyGuid 
 * @param info 
 */


data class DeviceList (

    @field:JsonProperty("guid")
    val guid: kotlin.String? = null,

    @field:JsonProperty("uniqueId")
    val uniqueId: kotlin.String? = null,

    @field:JsonProperty("displayName")
    val displayName: kotlin.String? = null,

    @field:JsonProperty("isConnected")
    val isConnected: kotlin.Boolean? = null,

    @field:JsonProperty("lastactivityDate")
    val lastactivityDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("isActive")
    val isActive: kotlin.Boolean? = null,

    @field:JsonProperty("firmwareupgradeGuid")
    val firmwareupgradeGuid: kotlin.String? = null,

    @field:JsonProperty("deviceTemplateGuid")
    val deviceTemplateGuid: kotlin.String? = null,

    @field:JsonProperty("authType")
    val authType: kotlin.Int? = null,

    @field:JsonProperty("authenticationType")
    val authenticationType: kotlin.String? = null,

    @field:JsonProperty("messageVersion")
    val messageVersion: kotlin.String? = null,

    @field:JsonProperty("isSolutionTemplate")
    val isSolutionTemplate: kotlin.Boolean? = null,

    @field:JsonProperty("solutionName")
    val solutionName: kotlin.String? = null,

    @field:JsonProperty("deviceInfo")
    val deviceInfo: kotlin.Any? = null,

    @field:JsonProperty("deviceTemplateName")
    val deviceTemplateName: kotlin.String? = null,

    @field:JsonProperty("reportingTo")
    val reportingTo: kotlin.String? = null,

    @field:JsonProperty("entityName")
    val entityName: kotlin.String? = null,

    @field:JsonProperty("IsAcquired")
    val isAcquired: kotlin.Boolean? = null,

    @field:JsonProperty("childDeviceCount")
    val childDeviceCount: kotlin.Int? = null,

    @field:JsonProperty("isType2Support")
    val isType2Support: kotlin.Boolean? = null,

    @field:JsonProperty("IsAllottedDevice")
    val isAllottedDevice: kotlin.Int? = null,

    @field:JsonProperty("allottedDevicePermission")
    val allottedDevicePermission: kotlin.Int? = null,

    @field:JsonProperty("count")
    val count: kotlin.Int? = null,

    @field:JsonProperty("isSharedDevice")
    val isSharedDevice: kotlin.Boolean? = null,

    @field:JsonProperty("properties")
    val properties: kotlin.collections.List<DeviceProperty>? = null,

    @field:JsonProperty("deviceStatus")
    val deviceStatus: kotlin.String? = null,

    @field:JsonProperty("recentAttrValue")
    val recentAttrValue: kotlin.Any? = null,

    @field:JsonProperty("isDpsDevice")
    val isDpsDevice: kotlin.Boolean? = null,

    @field:JsonProperty("lastConnection")
    val lastConnection: java.time.OffsetDateTime? = null,

    @field:JsonProperty("lastCommunication")
    val lastCommunication: java.time.OffsetDateTime? = null,

    @field:JsonProperty("solutionGuid")
    val solutionGuid: kotlin.String? = null,

    @field:JsonProperty("groupName")
    val groupName: kotlin.String? = null,

    @field:JsonProperty("productName")
    val productName: kotlin.String? = null,

    @field:JsonProperty("parentCompanyGuid")
    val parentCompanyGuid: java.util.UUID? = null,

    @field:JsonProperty("info")
    val info: kotlin.collections.List<OutputparamListResponse>? = null

)

