/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param deviceCertificate Byte array of device certificate file(Only .pfx file allowed).
 * @param deviceCertificatePassword Password of device certificate
 * @param rootCAIndividualCertificateGuid root CA Individual certificate guid.
 */

data class DeviceAcquireRequest(

    /* Byte array of device certificate file(Only .pfx file allowed). */
    @field:JsonProperty("deviceCertificate")
    val deviceCertificate: kotlin.ByteArray? = null,

    /* Password of device certificate */
    @field:JsonProperty("deviceCertificatePassword")
    val deviceCertificatePassword: kotlin.String? = null,

    /* root CA Individual certificate guid. */
    @field:JsonProperty("rootCAIndividualCertificateGuid")
    val rootCAIndividualCertificateGuid: kotlin.String? = null,

)
