/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param entity * @param counters */

data class DeviceStatistic(

    @field:JsonProperty("entity")
    val entity: kotlin.String? = null,

    @field:JsonProperty("counters")
    val counters: DeviceCounters? = null,

)
