/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param reportedValue * @param desiredValue * @param desiredUpdatedDate * @param reportedUpdatedDate * @param uniqueId * @param localName */

data class DeviceLookupByTemplate(

    @field:JsonProperty("reportedValue")
    val reportedValue: kotlin.String? = null,

    @field:JsonProperty("desiredValue")
    val desiredValue: kotlin.String? = null,

    @field:JsonProperty("desiredUpdatedDate")
    val desiredUpdatedDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("reportedUpdatedDate")
    val reportedUpdatedDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("uniqueId")
    val uniqueId: kotlin.String? = null,

    @field:JsonProperty("localName")
    val localName: kotlin.String? = null,

)
