/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param active 
 * @param inActive 
 * @param connected 
 * @param disConnected 
 * @param acquired 
 * @param available 
 * @param total 
 * @param released 
 * @param unAssociatedDevice 
 */


data class DeviceCounters (

    @field:JsonProperty("active")
    val active: kotlin.Int? = null,

    @field:JsonProperty("inActive")
    val inActive: kotlin.Int? = null,

    @field:JsonProperty("connected")
    val connected: kotlin.Int? = null,

    @field:JsonProperty("disConnected")
    val disConnected: kotlin.Int? = null,

    @field:JsonProperty("acquired")
    val acquired: kotlin.Int? = null,

    @field:JsonProperty("available")
    val available: kotlin.Int? = null,

    @field:JsonProperty("total")
    val total: kotlin.Int? = null,

    @field:JsonProperty("released")
    val released: kotlin.Int? = null,

    @field:JsonProperty("unAssociatedDevice")
    val unAssociatedDevice: kotlin.Int? = null

)

