/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param errorText 
 * @param deviceGuid 
 * @param oldEntityGuid 
 * @param entityGuid 
 * @param uniqueId 
 * @param deviceTemplateGuid 
 * @param firmwareUpgradeGuid 
 * @param displayName 
 * @param isActive 
 * @param isDeleted 
 * @param note 
 * @param isAcquired 
 * @param parentDeviceGuid 
 */


data class DeviceEntityBulkUpdate (

    @field:JsonProperty("errorText")
    val errorText: kotlin.String? = null,

    @field:JsonProperty("deviceGuid")
    val deviceGuid: kotlin.String? = null,

    @field:JsonProperty("oldEntityGuid")
    val oldEntityGuid: kotlin.String? = null,

    @field:JsonProperty("entityGuid")
    val entityGuid: kotlin.String? = null,

    @field:JsonProperty("uniqueId")
    val uniqueId: kotlin.String? = null,

    @field:JsonProperty("deviceTemplateGuid")
    val deviceTemplateGuid: kotlin.String? = null,

    @field:JsonProperty("firmwareUpgradeGuid")
    val firmwareUpgradeGuid: kotlin.String? = null,

    @field:JsonProperty("displayName")
    val displayName: kotlin.String? = null,

    @field:JsonProperty("isActive")
    val isActive: kotlin.Boolean? = null,

    @field:JsonProperty("isDeleted")
    val isDeleted: kotlin.Boolean? = null,

    @field:JsonProperty("note")
    val note: kotlin.String? = null,

    @field:JsonProperty("isAcquired")
    val isAcquired: kotlin.Int? = null,

    @field:JsonProperty("parentDeviceGuid")
    val parentDeviceGuid: kotlin.String? = null

)

