/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param status 
 * @param changeDate 
 * @param changeBy 
 * @param messageText 
 */


data class DeviceLifeCycle (

    @field:JsonProperty("status")
    val status: kotlin.String? = null,

    @field:JsonProperty("changeDate")
    val changeDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("changeBy")
    val changeBy: kotlin.String? = null,

    @field:JsonProperty("messageText")
    val messageText: kotlin.String? = null

)

