/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param displayName The display name of device.
 * @param entityGuid The entityGuid of device.
 * @param note The note of the device.
 * @param properties The custom properties of device.
 * @param xmlProperties */

data class DeviceUpdateRequest(

    /* The display name of device. */
    @field:JsonProperty("displayName")
    val displayName: kotlin.String,

    /* The entityGuid of device. */
    @field:JsonProperty("entityGuid")
    val entityGuid: kotlin.String,

    /* The note of the device. */
    @field:JsonProperty("note")
    val note: kotlin.String? = null,

    /* The custom properties of device. */
    @field:JsonProperty("properties")
    val properties: kotlin.collections.List<PropertyValue>? = null,

    @field:JsonProperty("xmlProperties")
    val xmlProperties: kotlin.Any? = null,

)
