/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param guid 
 * @param methodName 
 * @param responseTimeoutSecond 
 */


data class DirectMethodLookup (

    @field:JsonProperty("guid")
    val guid: kotlin.String? = null,

    @field:JsonProperty("methodName")
    val methodName: kotlin.String? = null,

    @field:JsonProperty("responseTimeoutSecond")
    val responseTimeoutSecond: kotlin.Int? = null

)

