/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param templateGuid Template Guid
 * @param methodName Method Name
 * @param responseTimeoutInSeconds Response timeout seconds
 */


data class DirectMethodUpdateRequest (

    /* Template Guid */
    @field:JsonProperty("templateGuid")
    val templateGuid: kotlin.String,

    /* Method Name */
    @field:JsonProperty("methodName")
    val methodName: kotlin.String,

    /* Response timeout seconds */
    @field:JsonProperty("responseTimeoutInSeconds")
    val responseTimeoutInSeconds: kotlin.Int

)

