/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param type Group Type Guid.
 * @param name Group Name
 * @param sphereGroup */

data class GroupCreateRequest(

    /* Group Type Guid. */
    @field:JsonProperty("type")
    val type: kotlin.String,

    /* Group Name */
    @field:JsonProperty("name")
    val name: kotlin.String,

    @field:JsonProperty("sphereGroup")
    val sphereGroup: SphereDeviceGroupModel? = null,

)
