/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models

import com.thealvistar.iotconnect.device.client.models.SphereDeviceGroupModel

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param guid 
 * @param name 
 * @param typeGuid 
 * @param typeName 
 * @param isActive 
 * @param companyGuid 
 * @param isDeleted 
 * @param createdDate 
 * @param createdBy 
 * @param updatedDate 
 * @param updatedBy 
 * @param sphereGroup 
 */


data class GroupGet (

    @field:JsonProperty("guid")
    val guid: kotlin.String? = null,

    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    @field:JsonProperty("typeGuid")
    val typeGuid: kotlin.String? = null,

    @field:JsonProperty("typeName")
    val typeName: kotlin.String? = null,

    @field:JsonProperty("isActive")
    val isActive: kotlin.Boolean? = null,

    @field:JsonProperty("companyGuid")
    val companyGuid: kotlin.String? = null,

    @field:JsonProperty("isDeleted")
    val isDeleted: kotlin.Boolean? = null,

    @field:JsonProperty("createdDate")
    val createdDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("createdBy")
    val createdBy: kotlin.String? = null,

    @field:JsonProperty("updatedDate")
    val updatedDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("updatedBy")
    val updatedBy: kotlin.String? = null,

    @field:JsonProperty("sphereGroup")
    val sphereGroup: SphereDeviceGroupModel? = null

)

