/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param permission Permission list, Represents a dictionary of pemission(true/false) accessed by permission name.   Note : Here, 'view' and 'operation' are available permission and at least one permission is required Eg. {\"view\" : true, \"operation\" : false}
 */

data class GroupUserUpdateRequest(

    /* Permission list, Represents a dictionary of pemission(true/false) accessed by permission name.   Note : Here, 'view' and 'operation' are available permission and at least one permission is required Eg. {\"view\" : true, \"operation\" : false} */
    @field:JsonProperty("permission")
    val permission: kotlin.collections.Map<kotlin.String, kotlin.Any>,

)
