/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models

import com.thealvistar.iotconnect.device.client.models.StatusModel

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param error 
 * @param success 
 */


data class GroupDeviceCreate (

    @field:JsonProperty("error")
    val error: kotlin.collections.List<StatusModel>? = null,

    @field:JsonProperty("success")
    val success: kotlin.collections.List<StatusModel>? = null

)

