/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param groupGuid Group Guid
 * @param deviceGuids Device Guid List
 */

data class GroupDeviceCreateRequest(

    /* Group Guid */
    @field:JsonProperty("groupGuid")
    val groupGuid: kotlin.String,

    /* Device Guid List */
    @field:JsonProperty("deviceGuids")
    val deviceGuids: kotlin.collections.List<kotlin.String>,

)
