/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param deviceupdate * @param submittedDate * @param status */

data class ImportHistory(

    @field:JsonProperty("deviceupdate")
    val deviceupdate: DeviceUpdate? = null,

    @field:JsonProperty("submittedDate")
    val submittedDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("status")
    val status: kotlin.String? = null,

)
