/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param uniqueId 
 * @param date 
 * @param type 
 * @param error 
 * @param errorDetail 
 * @param `data` 
 */


data class InvalidDeviceCommunicationList (

    @field:JsonProperty("uniqueId")
    val uniqueId: kotlin.String? = null,

    @field:JsonProperty("date")
    val date: java.time.OffsetDateTime? = null,

    @field:JsonProperty("type")
    val type: kotlin.String? = null,

    @field:JsonProperty("error")
    val error: kotlin.String? = null,

    @field:JsonProperty("errorDetail")
    val errorDetail: kotlin.String? = null,

    @field:JsonProperty("data")
    val `data`: kotlin.String? = null

)

