/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param fName 
 * @param dName 
 * @param `value` 
 */


data class OutputparamListResponse (

    @field:JsonProperty("fName")
    val fName: kotlin.String? = null,

    @field:JsonProperty("dName")
    val dName: kotlin.String? = null,

    @field:JsonProperty("value")
    val `value`: kotlin.Any? = null

)

