/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param guid The custom property guid
 * @param `value` The custom property value
 */

data class PropertyValue(

    /* The custom property guid */
    @field:JsonProperty("guid")
    val guid: kotlin.String,

    /* The custom property value */
    @field:JsonProperty("value")
    val `value`: kotlin.String? = null,

)
