/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param interval * @param intervalUnit * @param roleGuids * @param userGuids * @param guid */

data class RuleAudienceModel(

    @field:JsonProperty("interval")
    val interval: kotlin.Int? = null,

    @field:JsonProperty("intervalUnit")
    val intervalUnit: kotlin.Int? = null,

    @field:JsonProperty("roleGuids")
    val roleGuids: kotlin.collections.List<kotlin.String>? = null,

    @field:JsonProperty("userGuids")
    val userGuids: kotlin.collections.List<kotlin.String>? = null,

    @field:JsonProperty("guid")
    val guid: kotlin.String? = null,

)
