/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param guid 
 * @param condition 
 * @param bitValue 
 * @param `operator` 
 */


data class RuleCondition (

    @field:JsonProperty("guid")
    val guid: java.util.UUID? = null,

    @field:JsonProperty("condition")
    val condition: kotlin.String? = null,

    @field:JsonProperty("bitValue")
    val bitValue: kotlin.Int? = null,

    @field:JsonProperty("operator")
    val `operator`: kotlin.String? = null

)

