/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param isActive Active status, send false for making rule inactive.
 */


data class RuleUpdateStatusRequest (

    /* Active status, send false for making rule inactive. */
    @field:JsonProperty("isActive")
    val isActive: kotlin.Boolean

)

