/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param isValid * @param attributes * @param tags */

data class RuleVerifyResponse(

    @field:JsonProperty("isValid")
    val isValid: kotlin.Boolean? = null,

    @field:JsonProperty("attributes")
    val attributes: kotlin.collections.List<kotlin.String>? = null,

    @field:JsonProperty("tags")
    val tags: kotlin.collections.List<kotlin.String>? = null,

)
