/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models

import com.thealvistar.iotconnect.device.client.models.OutputparamListResponse

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param guid 
 * @param name 
 * @param template 
 * @param entity 
 * @param ruleType 
 * @param conditionText 
 * @param userCount 
 * @param roleCount 
 * @param createdby 
 * @param updatedby 
 * @param createddate 
 * @param updateddate 
 * @param isActive 
 * @param snoozeTime 
 * @param isSolutionTemplate 
 * @param solutionName 
 * @param info 
 */


data class RuleList (

    @field:JsonProperty("guid")
    val guid: kotlin.String? = null,

    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    @field:JsonProperty("template")
    val template: kotlin.String? = null,

    @field:JsonProperty("entity")
    val entity: kotlin.String? = null,

    @field:JsonProperty("ruleType")
    val ruleType: kotlin.String? = null,

    @field:JsonProperty("conditionText")
    val conditionText: kotlin.String? = null,

    @field:JsonProperty("userCount")
    val userCount: kotlin.Int? = null,

    @field:JsonProperty("roleCount")
    val roleCount: kotlin.Int? = null,

    @field:JsonProperty("createdby")
    val createdby: kotlin.String? = null,

    @field:JsonProperty("updatedby")
    val updatedby: kotlin.String? = null,

    @field:JsonProperty("createddate")
    val createddate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("updateddate")
    val updateddate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("isActive")
    val isActive: kotlin.Boolean? = null,

    @field:JsonProperty("snoozeTime")
    val snoozeTime: kotlin.Int? = null,

    @field:JsonProperty("isSolutionTemplate")
    val isSolutionTemplate: kotlin.Boolean? = null,

    @field:JsonProperty("solutionName")
    val solutionName: kotlin.String? = null,

    @field:JsonProperty("info")
    val info: kotlin.collections.List<OutputparamListResponse>? = null

)

