/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param guid 
 * @param name 
 * @param localName 
 * @param defaultValue 
 * @param dataTypeName 
 * @param dataValidation 
 * @param isReadOnly 
 */


data class SettingLookup (

    @field:JsonProperty("guid")
    val guid: kotlin.String? = null,

    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    @field:JsonProperty("localName")
    val localName: kotlin.String? = null,

    @field:JsonProperty("defaultValue")
    val defaultValue: kotlin.String? = null,

    @field:JsonProperty("dataTypeName")
    val dataTypeName: kotlin.String? = null,

    @field:JsonProperty("dataValidation")
    val dataValidation: kotlin.String? = null,

    @field:JsonProperty("isReadOnly")
    val isReadOnly: kotlin.Boolean? = null

)

