/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param name Twin property name
 * @param dataTypeGuid Twin property's datatype guid. Note : Object datatype is not allowed for twin property.
 * @param deviceTemplateGuid Associated Device Template Guid
 * @param localName Twin property key
 * @param defaultValue Default value for twin property
 * @param dataValidation Data validation for the twin property values.   Type validation values and/or validation ranges separated by commas.<div> For example: </div><div>  1, 2, 10 to 20 </div> -10 to -5, -15 <div> Red, Green, Blue</div>
 * @param isReadOnly 
 */


data class SettingCreateRequest (

    /* Twin property name */
    @field:JsonProperty("name")
    val name: kotlin.String,

    /* Twin property's datatype guid. Note : Object datatype is not allowed for twin property. */
    @field:JsonProperty("dataTypeGuid")
    val dataTypeGuid: kotlin.String,

    /* Associated Device Template Guid */
    @field:JsonProperty("deviceTemplateGuid")
    val deviceTemplateGuid: kotlin.String,

    /* Twin property key */
    @field:JsonProperty("localName")
    val localName: kotlin.String,

    /* Default value for twin property */
    @field:JsonProperty("defaultValue")
    val defaultValue: kotlin.String,

    /* Data validation for the twin property values.   Type validation values and/or validation ranges separated by commas.<div> For example: </div><div>  1, 2, 10 to 20 </div> -10 to -5, -15 <div> Red, Green, Blue</div> */
    @field:JsonProperty("dataValidation")
    val dataValidation: kotlin.String? = null,

    @field:JsonProperty("isReadOnly")
    val isReadOnly: kotlin.Boolean? = null

)

