/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param guid 
 * @param name 
 * @param dataTypeGuid 
 * @param createdDate 
 * @param createdby 
 * @param updatedDate 
 * @param localName 
 * @param defaultValue 
 * @param dataValidation 
 * @param tag 
 * @param isReadOnly 
 * @param dataTypeName 
 */


data class SettingList (

    @field:JsonProperty("guid")
    val guid: kotlin.String? = null,

    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    @field:JsonProperty("dataTypeGuid")
    val dataTypeGuid: kotlin.String? = null,

    @field:JsonProperty("createdDate")
    val createdDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("createdby")
    val createdby: kotlin.String? = null,

    @field:JsonProperty("updatedDate")
    val updatedDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("localName")
    val localName: kotlin.String? = null,

    @field:JsonProperty("defaultValue")
    val defaultValue: kotlin.Any? = null,

    @field:JsonProperty("dataValidation")
    val dataValidation: kotlin.String? = null,

    @field:JsonProperty("tag")
    val tag: kotlin.String? = null,

    @field:JsonProperty("isReadOnly")
    val isReadOnly: kotlin.Boolean? = null,

    @field:JsonProperty("dataTypeName")
    val dataTypeName: kotlin.String? = null

)

