/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param desc 
 * @param osFeedType 
 * @param updatePolicy 
 * @param productName 
 */


data class SphereDeviceGroupListModel (

    @field:JsonProperty("desc")
    val desc: kotlin.String? = null,

    @field:JsonProperty("osFeedType")
    val osFeedType: kotlin.String? = null,

    @field:JsonProperty("updatePolicy")
    val updatePolicy: kotlin.String? = null,

    @field:JsonProperty("productName")
    val productName: kotlin.String? = null

)

