/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param deviceGuid 
 * @param deviceId 
 */


data class SyncSphereGroupAndProductRequest (

    @field:JsonProperty("deviceGuid")
    val deviceGuid: java.util.UUID? = null,

    @field:JsonProperty("deviceId")
    val deviceId: kotlin.String? = null

)

