/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param guid 
 * @param name 
 * @param datatypeGuid 
 * @param dataType 
 * @param createdDate 
 * @param createdBy 
 * @param updatedDate 
 * @param updatedBy 
 * @param localName 
 * @param defaultValue 
 * @param dataValidation 
 * @param isReadOnly 
 */


data class TemplateSettingData (

    @field:JsonProperty("guid")
    val guid: java.util.UUID? = null,

    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    @field:JsonProperty("datatypeGuid")
    val datatypeGuid: java.util.UUID? = null,

    @field:JsonProperty("dataType")
    val dataType: kotlin.String? = null,

    @field:JsonProperty("createdDate")
    val createdDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("createdBy")
    val createdBy: java.util.UUID? = null,

    @field:JsonProperty("updatedDate")
    val updatedDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("updatedBy")
    val updatedBy: java.util.UUID? = null,

    @field:JsonProperty("localName")
    val localName: kotlin.String? = null,

    @field:JsonProperty("defaultValue")
    val defaultValue: kotlin.Any? = null,

    @field:JsonProperty("dataValidation")
    val dataValidation: kotlin.String? = null,

    @field:JsonProperty("isReadOnly")
    val isReadOnly: kotlin.Boolean? = null

)

