/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param condition * @param createdDate * @param deviceGuid * @param entityGuid * @param isAllottedDevice * @param notificationText * @param ruleName * @param severityLevel * @param telemetry * @param uniqueId */

data class TemplateDeviceNotification(

    @field:JsonProperty("condition")
    val condition: kotlin.String? = null,

    @field:JsonProperty("createdDate")
    val createdDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("deviceGuid")
    val deviceGuid: kotlin.String? = null,

    @field:JsonProperty("entityGuid")
    val entityGuid: kotlin.String? = null,

    @field:JsonProperty("isAllottedDevice")
    val isAllottedDevice: kotlin.Int? = null,

    @field:JsonProperty("notificationText")
    val notificationText: kotlin.String? = null,

    @field:JsonProperty("ruleName")
    val ruleName: kotlin.String? = null,

    @field:JsonProperty("severityLevel")
    val severityLevel: kotlin.String? = null,

    @field:JsonProperty("telemetry")
    val telemetry: kotlin.Any? = null,

    @field:JsonProperty("uniqueId")
    val uniqueId: kotlin.String? = null,

)
