/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param code Unique device template code. Template code must be alphanumeric and must start with the alphabet .
 * @param isEdgeSupport For devices with edge support
 * @param authType Authentication Type - 1: Key, 2: CA Signed Certificate, 3: Self Signed Certificate, 4: TPM, 5: Symmetric Key,6: DDKG,7: BootstrapCertificate, 8: PKISignature
 * @param name Device template name
 * @param tag For Gateway supported Devices.   It should be alphanumeric with allowed two consecutive '_' and must be started with the alphabet.   Eg. Temperature, Humadity, oxygenIn1, Temperature_In, Temperature__Out, Oxygen_In__1  etc.
 * @param dataLength For devices with low bandwidth support
 * @param isIotEdgeEnable True to devices is Azure IoTEdge.
 * @param messageVersion 
 * @param isSphere 
 * @param trustedPartnerGuid 
 * @param firmwareguid Firmware hardware version guid
 */


data class TemplateCreateRequest (

    /* Unique device template code. Template code must be alphanumeric and must start with the alphabet . */
    @field:JsonProperty("code")
    val code: kotlin.String,

    /* For devices with edge support */
    @field:JsonProperty("isEdgeSupport")
    val isEdgeSupport: kotlin.Boolean,

    /* Authentication Type - 1: Key, 2: CA Signed Certificate, 3: Self Signed Certificate, 4: TPM, 5: Symmetric Key,6: DDKG,7: BootstrapCertificate, 8: PKISignature */
    @field:JsonProperty("authType")
    val authType: kotlin.Int,

    /* Device template name */
    @field:JsonProperty("name")
    val name: kotlin.String,

    /* For Gateway supported Devices.   It should be alphanumeric with allowed two consecutive '_' and must be started with the alphabet.   Eg. Temperature, Humadity, oxygenIn1, Temperature_In, Temperature__Out, Oxygen_In__1  etc. */
    @field:JsonProperty("tag")
    val tag: kotlin.String? = null,

    /* For devices with low bandwidth support */
    @field:JsonProperty("dataLength")
    val dataLength: kotlin.Int? = null,

    /* True to devices is Azure IoTEdge. */
    @field:JsonProperty("isIotEdgeEnable")
    val isIotEdgeEnable: kotlin.Boolean? = null,

    @field:JsonProperty("messageVersion")
    val messageVersion: kotlin.String? = null,

    @field:JsonProperty("isSphere")
    val isSphere: kotlin.Boolean? = null,

    @field:JsonProperty("trustedPartnerGuid")
    val trustedPartnerGuid: java.util.UUID? = null,

    /* Firmware hardware version guid */
    @field:JsonProperty("firmwareguid")
    val firmwareguid: kotlin.String? = null

)

