/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param guid * @param name * @param command * @param createdDate * @param createdBy * @param updatedDate * @param updatedBy * @param requiredParam * @param requiredAck * @param isOTACommand * @param isTemplateCommandUsed * @param tag */

data class TemplateCommandData(

    @field:JsonProperty("guid")
    val guid: java.util.UUID? = null,

    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    @field:JsonProperty("command")
    val command: kotlin.String? = null,

    @field:JsonProperty("createdDate")
    val createdDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("createdBy")
    val createdBy: java.util.UUID? = null,

    @field:JsonProperty("updatedDate")
    val updatedDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("updatedBy")
    val updatedBy: java.util.UUID? = null,

    @field:JsonProperty("requiredParam")
    val requiredParam: kotlin.Boolean? = null,

    @field:JsonProperty("requiredAck")
    val requiredAck: kotlin.Boolean? = null,

    @field:JsonProperty("isOTACommand")
    val isOTACommand: kotlin.Boolean? = null,

    @field:JsonProperty("isTemplateCommandUsed")
    val isTemplateCommandUsed: kotlin.Boolean? = null,

    @field:JsonProperty("tag")
    val tag: kotlin.String? = null,

)
