/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param name Device template name
 * @param firmwareguid Firmware hardware version guid
 */

data class TemplateUpdateRequest(

    /* Device template name */
    @field:JsonProperty("name")
    val name: kotlin.String,

    /* Firmware hardware version guid */
    @field:JsonProperty("firmwareguid")
    val firmwareguid: kotlin.String? = null,

)
