/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param dataFrequency DataFrequency. Default value is 60.
 * @param description Description.
 * @param fileSupport File support. Default value is false.
 */


data class TemplatePropertyRequest (

    /* DataFrequency. Default value is 60. */
    @field:JsonProperty("dataFrequency")
    val dataFrequency: kotlin.Int? = null,

    /* Description. */
    @field:JsonProperty("description")
    val description: kotlin.String? = null,

    /* File support. Default value is false. */
    @field:JsonProperty("fileSupport")
    val fileSupport: kotlin.Boolean? = false

)

