/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param guid 
 * @param code 
 * @param name 
 * @param description 
 * @param firmwareGuid 
 * @param createdDate 
 * @param updatedDate 
 * @param attributeCount 
 * @param settingCount 
 * @param commandCount 
 * @param deviceCount 
 * @param ruleCount 
 * @param isValidateTemplate 
 * @param isValidEdgeSupport 
 * @param isValidType2Support 
 * @param tag 
 * @param authType 
 * @param isEdgeSupport 
 * @param gatewaySupport 
 * @param isLowBandwidth 
 * @param isIotEdgeEnable 
 * @param isSolutionTemplate 
 * @param solutionName 
 * @param messageVersion 
 * @param fileSupport 
 * @param directMethodCount 
 * @param authenticationType 
 */


data class TemplateList (

    @field:JsonProperty("guid")
    val guid: kotlin.String? = null,

    @field:JsonProperty("code")
    val code: kotlin.String? = null,

    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    @field:JsonProperty("description")
    val description: kotlin.String? = null,

    @field:JsonProperty("firmwareGuid")
    val firmwareGuid: kotlin.String? = null,

    @field:JsonProperty("createdDate")
    val createdDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("updatedDate")
    val updatedDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("attributeCount")
    val attributeCount: kotlin.Int? = null,

    @field:JsonProperty("settingCount")
    val settingCount: kotlin.Int? = null,

    @field:JsonProperty("commandCount")
    val commandCount: kotlin.Int? = null,

    @field:JsonProperty("deviceCount")
    val deviceCount: kotlin.Int? = null,

    @field:JsonProperty("ruleCount")
    val ruleCount: kotlin.Int? = null,

    @field:JsonProperty("isValidateTemplate")
    val isValidateTemplate: kotlin.Boolean? = null,

    @field:JsonProperty("isValidEdgeSupport")
    val isValidEdgeSupport: kotlin.Boolean? = null,

    @field:JsonProperty("isValidType2Support")
    val isValidType2Support: kotlin.Boolean? = null,

    @field:JsonProperty("tag")
    val tag: kotlin.String? = null,

    @field:JsonProperty("authType")
    val authType: kotlin.Int? = null,

    @field:JsonProperty("isEdgeSupport")
    val isEdgeSupport: kotlin.Boolean? = null,

    @field:JsonProperty("gatewaySupport")
    val gatewaySupport: kotlin.Boolean? = null,

    @field:JsonProperty("isLowBandwidth")
    val isLowBandwidth: kotlin.Boolean? = null,

    @field:JsonProperty("isIotEdgeEnable")
    val isIotEdgeEnable: kotlin.Boolean? = null,

    @field:JsonProperty("isSolutionTemplate")
    val isSolutionTemplate: kotlin.Boolean? = null,

    @field:JsonProperty("solutionName")
    val solutionName: kotlin.String? = null,

    @field:JsonProperty("messageVersion")
    val messageVersion: kotlin.String? = null,

    @field:JsonProperty("fileSupport")
    val fileSupport: kotlin.Boolean? = null,

    @field:JsonProperty("directMethodCount")
    val directMethodCount: kotlin.Int? = null,

    @field:JsonProperty("authenticationType")
    val authenticationType: kotlin.String? = null

)

