/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param guid * @param templateCode * @param templateName * @param createdDate * @param createdBy * @param updatedDate * @param updatedBy * @param firmwareGuid * @param firmwareName * @param isEdgeSupport * @param reqAttrPush * @param reqSettingPush * @param authType * @param isType2Support * @param tag * @param attrXml * @param attributes * @param settingXml * @param settings * @param commandXml * @param commands * @param directMethodXml * @param directMethods * @param isValidateTemplate * @param isValidEdgeSupport * @param isValidType2Support * @param isAttachedWithDevice * @param dataLength * @param isLowBandwidth * @param isIotEdgeEnable * @param isSolutionTemplate * @param messageVersion * @param `property` */

data class TemplateDetail(

    @field:JsonProperty("guid")
    val guid: kotlin.String? = null,

    @field:JsonProperty("templateCode")
    val templateCode: kotlin.String? = null,

    @field:JsonProperty("templateName")
    val templateName: kotlin.String? = null,

    @field:JsonProperty("createdDate")
    val createdDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("createdBy")
    val createdBy: kotlin.String? = null,

    @field:JsonProperty("updatedDate")
    val updatedDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("updatedBy")
    val updatedBy: kotlin.String? = null,

    @field:JsonProperty("firmwareGuid")
    val firmwareGuid: kotlin.String? = null,

    @field:JsonProperty("firmwareName")
    val firmwareName: kotlin.String? = null,

    @field:JsonProperty("isEdgeSupport")
    val isEdgeSupport: kotlin.Boolean? = null,

    @field:JsonProperty("reqAttrPush")
    val reqAttrPush: kotlin.Boolean? = null,

    @field:JsonProperty("reqSettingPush")
    val reqSettingPush: kotlin.Any? = null,

    @field:JsonProperty("authType")
    val authType: kotlin.Int? = null,

    @field:JsonProperty("isType2Support")
    val isType2Support: kotlin.Boolean? = null,

    @field:JsonProperty("tag")
    val tag: kotlin.String? = null,

    @field:JsonProperty("attrXml")
    val attrXml: kotlin.String? = null,

    @field:JsonProperty("attributes")
    val attributes: kotlin.Any? = null,

    @field:JsonProperty("settingXml")
    val settingXml: kotlin.String? = null,

    @field:JsonProperty("settings")
    val settings: kotlin.collections.List<TemplateSettingData>? = null,

    @field:JsonProperty("commandXml")
    val commandXml: kotlin.String? = null,

    @field:JsonProperty("commands")
    val commands: kotlin.collections.List<TemplateCommandData>? = null,

    @field:JsonProperty("directMethodXml")
    val directMethodXml: kotlin.String? = null,

    @field:JsonProperty("directMethods")
    val directMethods: kotlin.collections.List<TemplateDirecteMethodData>? = null,

    @field:JsonProperty("isValidateTemplate")
    val isValidateTemplate: kotlin.Int? = null,

    @field:JsonProperty("isValidEdgeSupport")
    val isValidEdgeSupport: kotlin.Int? = null,

    @field:JsonProperty("isValidType2Support")
    val isValidType2Support: kotlin.Int? = null,

    @field:JsonProperty("isAttachedWithDevice")
    val isAttachedWithDevice: kotlin.Boolean? = null,

    @field:JsonProperty("dataLength")
    val dataLength: kotlin.Int? = null,

    @field:JsonProperty("isLowBandwidth")
    val isLowBandwidth: kotlin.Boolean? = null,

    @field:JsonProperty("isIotEdgeEnable")
    val isIotEdgeEnable: kotlin.Boolean? = null,

    @field:JsonProperty("isSolutionTemplate")
    val isSolutionTemplate: kotlin.Boolean? = null,

    @field:JsonProperty("messageVersion")
    val messageVersion: kotlin.String? = null,

    @field:JsonProperty("property")
    val `property`: TemplateProperty? = null,

)
