/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param deviceTemplateGuid Associated Device Template Guid
 * @param isReadOnly */

data class TemplateSettingUpdateReadOnlyRequest(

    /* Associated Device Template Guid */
    @field:JsonProperty("deviceTemplateGuid")
    val deviceTemplateGuid: kotlin.String,

    @field:JsonProperty("isReadOnly")
    val isReadOnly: kotlin.Boolean? = null,

)
