/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param entityGuid Entity Guid
 * @param deviceTemplateGuid Group Guid
 * @param deviceGuids Device Guid List
 * @param isSphere 
 */


data class UnassociatedAttachBulkRequest (

    /* Entity Guid */
    @field:JsonProperty("entityGuid")
    val entityGuid: kotlin.String,

    /* Group Guid */
    @field:JsonProperty("deviceTemplateGuid")
    val deviceTemplateGuid: kotlin.String,

    /* Device Guid List */
    @field:JsonProperty("deviceGuids")
    val deviceGuids: kotlin.collections.List<kotlin.String>,

    @field:JsonProperty("isSphere")
    val isSphere: kotlin.Boolean? = null

)

