/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param guid * @param uniqueId * @param displayName * @param deviceTemplateGuid * @param entityName * @param createdBy * @param createdDate * @param deviceStatus * @param dpsInfoGuid * @param solutionGuid * @param isTpDevice */

data class UnassociatedDeviceList(

    @field:JsonProperty("guid")
    val guid: kotlin.String? = null,

    @field:JsonProperty("uniqueId")
    val uniqueId: kotlin.String? = null,

    @field:JsonProperty("displayName")
    val displayName: kotlin.String? = null,

    @field:JsonProperty("deviceTemplateGuid")
    val deviceTemplateGuid: kotlin.String? = null,

    @field:JsonProperty("entityName")
    val entityName: kotlin.String? = null,

    @field:JsonProperty("createdBy")
    val createdBy: kotlin.String? = null,

    @field:JsonProperty("createdDate")
    val createdDate: java.time.OffsetDateTime? = null,

    @field:JsonProperty("deviceStatus")
    val deviceStatus: kotlin.String? = null,

    @field:JsonProperty("dpsInfoGuid")
    val dpsInfoGuid: java.util.UUID? = null,

    @field:JsonProperty("solutionGuid")
    val solutionGuid: java.util.UUID? = null,

    @field:JsonProperty("isTpDevice")
    val isTpDevice: kotlin.Boolean? = null,

)
