/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.thealvistar.iotconnect.device.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param entityGuid Entity Guid
 * @param deviceTemplateGuid Template Guid
 * @param deviceGuid 
 * @param primaryThumbprint 
 * @param secondaryThumbprint 
 * @param deviceCertificateGuid The certificateGuid of devicetemplate.
 * @param endorsementKey The endorsementKey of TPM device. This field is required if device template authentication type is TPM.
 * @param isSphere 
 */


data class UnassociatedAttachRequest (

    /* Entity Guid */
    @field:JsonProperty("entityGuid")
    val entityGuid: kotlin.String,

    /* Template Guid */
    @field:JsonProperty("deviceTemplateGuid")
    val deviceTemplateGuid: kotlin.String,

    @field:JsonProperty("deviceGuid")
    val deviceGuid: kotlin.String,

    @field:JsonProperty("primaryThumbprint")
    val primaryThumbprint: kotlin.String? = null,

    @field:JsonProperty("secondaryThumbprint")
    val secondaryThumbprint: kotlin.String? = null,

    /* The certificateGuid of devicetemplate. */
    @field:JsonProperty("deviceCertificateGuid")
    val deviceCertificateGuid: kotlin.String? = null,

    /* The endorsementKey of TPM device. This field is required if device template authentication type is TPM. */
    @field:JsonProperty("endorsementKey")
    val endorsementKey: kotlin.String? = null,

    @field:JsonProperty("isSphere")
    val isSphere: kotlin.Boolean? = null

)

