/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.thealvistar.iotconnect.device.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * *
 * @param key * @param `value` */

data class WebHookBaseHeaderDetails(

    @field:JsonProperty("key")
    val key: kotlin.String,

    @field:JsonProperty("value")
    val `value`: kotlin.String,

)
